rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: password
  listeners:
    webhook:
      queue: webhook
  publishers:
    webhook:
      exchange: outbound
      routingkey: to_outbound_webhook
      queue: webhook